### ISSUE TITLE
Auto-redirect to mobilpay after order submit

### ISSUE THREAD

**Issue by rwkyyy** [alexboia/WC-MobilPayments-Card#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to see an auto 3/5 seconds redirect notice and action on the confirmation screen so the user can pay the order without an extra interaction

**Describe alternatives you've considered**
n/a

**Additional context**
Users do not always see the action button, that they have to pay.

**Comment by alexboia** [comment]
Done!
