### ISSUE TITLE
WooCommerce 5.6 Analytics -> Overview not working

### ISSUE THREAD

**Issue by rwkyyy** [alexboia/WC-MobilPayments-Card#16]
**Describe the bug**
As of WC 5.6, the analytics default tab (overview) does not load anymore, the react crashes (js), this is prob due to the widgets inserted by LivePayments plugin.

**To Reproduce**
1. Update WC to latest (5.6)
2. Go to Analytics -> Overview
3. Nothing loads (white page)

**Expected behavior**
Expecting analytics data to load

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version 92

**Smartphone (please complete the following information):**
N/A

**Additional context**
None needed

**Comment by rwkyyy** [comment]
a temporary fix is by disabling the cards rendering from:
`wc-mobilpayments-card/lib/MediaIncludes.php:198`

adding comments to that line, disables the load of the card and throws an error in the browser console, but it will allow admins to view the Overview tab.

**Comment by alexboia** [comment]
Done!

**Comment by alexboia** [comment]
@rwkyyy Issue resolved, just posting a reminder for testing the isolated patch.
